# cloudbuild.yaml

steps:
  # Step 1: Build the Docker images using docker-compose
  - name: 'docker/compose:1.29.2'
    args:
      - '-f'
      - 'docker-compose.yaml'
      - 'build'

  # Step 2: Push the Docker images to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['compose', '-f', 'docker-compose.yaml', 'push']

# Specify the images to be pushed to Container Registry
images:
  - 'gcr.io/$cicd-project-412702/service1'
  - 'gcr.io/$cicd-project-412702/service2'
