# steps:
#   # Build Services
#   - name: "gcr.io/cloud-builders/docker"
#     args: [
#       "build",
#       "-t",
#       "asia-southeast2-docker.pkg.dev/cicd-project-412702/python-app/my-app:${SHORT_SHA}",
#       ".",
#     ]

#   # Push images to Google Artifact Registry
#   - name: "gcr.io/cloud-builders/docker"
#     args: [
#       "push",
#       "asia-southeast2-docker.pkg.dev/cicd-project-412702/python-app/my-app:${SHORT_SHA}",
#       ".",
#     ]

# images:
#   - asia-southeast2-docker.pkg.dev/cicd-project-412702/python-app/my-app:${SHORT_SHA}

# options:
#   logging: CLOUD_LOGGING_ONLY

