steps:
  # Build Services
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast1-docker.pkg.dev/cicd-project-412702/python-repo/my-app:${SHORT_SHA}",
        ".",
      ]

  # Push images to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast1-docker.pkg.dev/cicd-project-412702/python-repo/my-app:${SHORT_SHA}",
        ".",
      ]

  images:
    - asia-southeast1-docker.pkg.dev/cicd-project-412702/python-repo/my-app:${SHORT_SHA}
