# cloudbuild.yaml

steps:
  - name: 'docker/compose:1.29.2'
    args:
      - '-f'
      - 'docker-compose.yml'
      - 'build'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['compose', '-f', 'docker-compose.yml', 'push']

images:
  - 'gcr.io/$cicd-project-412702/service1'
  - 'gcr.io/$cicd-project-412702/service2'

options:
  substitution_option: 'ALLOW_LOOSE'
  dynamic_substitutions: true

logging:
  - gcsBucket: "gs://cb-logs-cicd-project-412702"