# cloudbuild.yaml

steps:
  - name: 'docker/compose:1.29.2'
    args:
      - '-f'
      - 'docker-compose.yaml'
      - 'build'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['compose', '-f', 'docker-compose.yaml', 'push']

images:
  - 'gcr.io/$cicd-project-412702/service1'
  - 'gcr.io/$cicd-project-412702/service2'

options:
  build:
    service_account: cicd-trigger-github@cicd-project-412702.iam.gserviceaccount.com

logging:
  - gcsBucket: "gs://cb-logs-cicd-project-412702"

