steps:
  # Docker Compose Build
  - name: 'docker/compose:1.29.2'
    args: ['--file', 'docker-compose.yml', 'build']

  # Docker Compose Push
  - name: 'docker/compose:1.29.2'
    args: ['--file', 'docker-compose.yml', 'push']

  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: 
      - 'compute'
      - 'instances'
      - 'create-with-container'
      - 'my-vm-name'
      - '--container-image'
      - 'asia-southeast1.pkg.dev/${cicd-project-412702}/my-docker-repo/myimage'
options:
  logging:
    - 'gcsBucket: cicd-project-412702-logs'
