version: '3'

services:
  mysql:
    image: asia-southeast1-docker.pkg.dev/cicd-project-412702/demo/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'twitter'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

  script:
    image: asia-southeast1-docker.pkg.dev/cicd-project-412702/demo/python-script:latest
    depends_on:
      - mysql
