---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: python-script
      PROJECT_ID: cicd-project-412702
    steps:
    - name: Checkout
      uses: actions/checkoutv2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker-compose up -d

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker to GCR
      env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
