name: Build and Push Image to Google Cloud Platform

on:
  push:
    branches: 'main'

env:
  # GOOGLE_ZONE: secrets.GOOGLE_ZONE 
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Install the gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Build and push the Docker image to Artifact Registry
      run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
          docker build -t asia-southeast1-docker.pkg.dev/cicd-project-412702/demo -f script/Dockerfile . 
          docker push asia-southeast1-docker.pkg.dev/cicd-project-412702/demo/python-script
          
