name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: cicd-project-412702
  REGION: asia-southeast1
  GAR_LOCATION: asia-southeast1-docker.pkg.dev/cicd-project-412702/demo/

jobs:
  build-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build MySQL image
        run: docker build ./db/ --file ./db/Dockerfile --tag ${{ env.GAR_LOCATION }}/mysql:latest
        working-directory: .

      - name: Push MySQL image to Artifact Registry
        run: docker push ${{ env.GAR_LOCATION }}/mysql:latest

  build-and-push-python:
    runs-on: ubuntu-latest
    needs: build-mysql
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push Python image
        run: |
          docker build ./script/ --file ./script/Dockerfile --tag ${{ env.GAR_LOCATION }}/python-script:latest
          docker push ${{ env.GAR_LOCATION }}/python-script:latest
        working-directory: .



















































# name: Build and Push to Artifact Registry

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# env:
#   PROJECT_ID: cicd-project-412702
#   REGION: asia-southeast1
#   GAR_LOCATION: asia-southeast1-docker.pkg.dev/cicd-project-412702/demo/
#   WORKING_DIRECTORY: "${{ github.workspace }}"

# jobs:
#   build-push-artifact:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
      
#       - name: Authenticate with Google Cloud
#         id: auth
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      
#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
      
#       - name: Use gcloud CLI
#         run: gcloud info
      
#       - name: Docker auth
#         run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      
#       - name: Build and push images
#         run: |
#           docker-compose -f docker-compose.yml up --build
#           docker-compose -f docker-compose.yml push
#         working-directory: ${{ env.WORKING_DIRECTORY }}
        
 
